import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="container px-4 pt-5">
          
            <h1>Bienvenu sur code.io</h1>
            <p>Le blof communautaire des afficionados de développement web</p>
            <div className="row mt-5">
              <div className="col-12 col-sm-6" style={{minHeight:"200px"}}>
              <div className="card w-100 h-100">
                <div className="card-body">
                  <h5 className="card-title">Lisez les articles</h5>
                  <h6 className="card-subtitle mb-2 text-muted">Maximisez votre culture web</h6>
                  <p className="card-text">Chaque auteur tente de vous apporter le plus de valeur possible par article</p>
                  <Link href={"/blog"}>
                    <a className="card-link">Visiter le blog</a>
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-12 col-sm-6" style={{minHeight:"200px"}}>
              <div className="card w-100 h-100">
                <div className="card-body">
                  <h5 className="card-title">Faites un tour vers la liste de membres</h5>
                  <h6 className="card-subtitle mb-2 text-muted">Faites-vous des amis</h6>
                  <p className="card-text">Ajouter, invitez et discuter avec les différents membres</p>
                  <Link href={"/utilisateur"}>
                    <a className="card-link">Découvre la liste de membres</a>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  )
}
